apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: ssp-scheduler
        plugins:
          score:
            enabled:
            - name: "ssp-scheduler"
        pluginConfig:
        - name: "ssp-scheduler"
          args: {"master": "master", "kubeconfig": "kubeconfig"}
    leaderElection:
      leaderElect: true
      resourceName: ssp-scheduler
      resourceNamespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp-scheduler
  namespace: kube-system
  labels:
    component: ssp-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ssp-scheduler
  template:
    metadata:
      labels:
        component: ssp-scheduler
    spec:
      serviceAccountName: ssp-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: ssp-scheduler-pod
          image: tequilac/ssp-scheduler:latest
          imagePullPolicy: IfNotPresent
          args:
            - ssp-scheduler
            - --config=/scheduler/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /scheduler
